id: 8514cfec2c614ed3b4c0ff828e9d753d
initial_creation_type: ocr
source_metadata:
  volumes:
    040a1a8478a94359bfbed2c5d5d3316c:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སེམས་ཅན་མགུ་བར་བྱ་བའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
